### ISSUE TITLE
undefined function set_url_scheme()

### ISSUE THREAD

**Issue by pwrq** [joel-james/404-to-301#1]
Hello,
I am getting the following error on WordPress 3.3.1 using 404-to-301 version 2.0.9

Fatal error: Call to undefined function set_url_scheme() in /mypathtowordpresshome/wp-content/plugins/404-to-301/admin/core/class-wp-list-table.php on line 695

Thanks!

**Comment by joel-james** [comment]
Hello @pwrq 

What is your WordPress version?
