### ISSUE TITLE
Several issues

### ISSUE THREAD

**Issue by pedro-mendonca** [joel-james/404-to-301#16]
There are a few things I'm covering in this:

File `./includes/class-404-to-301.php~` I believe is temporary and is dangerous as isn't parsed by php.

*Thank you* message in the footer is badly formated - no space before the rate link, and just 2 stars? :)
It would be simpler to translators understand the context if this could be a single sentence.

Besides having the translation in wordpress.org, do you still want it here in /languages folder with the .pot catalog?

.pot catalog file is empty or damaged.

Uniformized `Current page` -> `Current Page` to keep coherent all pre existent strings.

At last, just a typo in my name you've written in changelog :)

As I'm writing this I'm correcting it, and I'm doing a PR in a minute.

**Comment by joel-james** [comment]
Pull request merged :+1: Closing the issue.
