### ISSUE TITLE
Missing image

### ISSUE THREAD

**Issue by pedro-mendonca** [joel-james/404-to-301#18]
Hi @joel-james 

I've updated with today release, there is an image missing: `404-to-301/admin/images/foxe.png`

This repo isn't up to date, are you planning to update it? Will this repo be abondoned and moved to WP SVN?

Regards

**Comment by pedro-mendonca** [comment]
Solved in v2.2.1
Thanks

**Comment by joel-james** [comment]
@pedro-mendonca Updated this repo too :+1:

**Comment by pedro-mendonca** [comment]
Thanks!
