### ISSUE TITLE
Bulk Action  > Clear Log bug

### ISSUE THREAD

**Issue by i-make-robots** [joel-james/404-to-301#2]
Latetest WP
404-2-301: Bulk Action  > Clear Log
Screen refreshes, first page of log still visible.
Force another refresh (click any link, F5, etc), logs are gone.

Please reorder events so the log is cleared before the page is generated to remove the extra refresh.  Current version feels unresponsive.

Loving this plugin, everything else about it rocks!

**Comment by joel-james** [comment]
@i-make-robots I have fixed the issue. Could you please update to the latest and let me know the feedback?

**Comment by i-make-robots** [comment]
First thing I notice is the number of lines per report page is now 5.  It was already short at 20.  Can you please give me a config option so I can set it to taste?  I'd like 50.

**Comment by i-make-robots** [comment]
I confirm your fix works.  Thank you!  Very responsive +1.

**Comment by joel-james** [comment]
@i-make-robots You can easily increase no. of items per page from screen options. Just click on the screen options in error log listing page and change the value. I will increase its default value through next updates. See the screenshot below.
![Screen Option](https://cloud.githubusercontent.com/assets/7510463/11917250/76b34f82-a725-11e5-8435-22ae079b754c.PNG)
