### ISSUE TITLE
No able to custom redirect

### ISSUE THREAD

**Issue by pedro-mendonca** [joel-james/404-to-301#22]
Hi

I've just updated this to v2.2.2. I still can't add custom redirect.
After saving, the custom redirect isn't there.

**Comment by joel-james** [comment]
DB upgrade doesn't work. We need to add [new column](https://github.com/joel-james/404-to-301/blob/master/includes/class-404-to-301-activator.php#L79) (`redirect`) to our 404 to 301 custom table. I will check this.

**Comment by joel-james** [comment]
Fixed this (#23)
