### ISSUE TITLE
include warning with PHP display_errors turned on.

### ISSUE THREAD

**Issue by i-make-robots** [Joel-James/404-to-301#36]
Warning: include_once(/var/www/marginallyclever.com/public/wp-content/plugins/404-to-301-master/includes/admin/class-jj4t3-reviews.php): failed to open stream: No such file or directory in /var/www/marginallyclever.com/public/wp-content/plugins/404-to-301-master/includes/class-jj-404-to-301.php on line 104

**Comment by i-make-robots** [comment]
afaik this is only visible in the admin panel.

**Comment by Joel-James** [comment]
Hi @i-make-robots,

See [line 104](https://github.com/Joel-James/404-to-301/blob/master/includes/class-jj-404-to-301.php#L104). There is no such call. Are you sure you are using master branch of this repo?

**Comment by i-make-robots** [comment]
I'm using whatever I get from the auto updates.

**Comment by Joel-James** [comment]
@i-make-robots which auto updater?

**Comment by i-make-robots** [comment]
Removed plugin, reinstalled, problem gone.  Sorry to bother you.

**Comment by i-make-robots** [comment]
stay awesome!
