### ISSUE TITLE
conflict with bbPress?

### ISSUE THREAD

**Issue by i-make-robots** [Joel-James/404-to-301#37]
latest WP, 404-to-301, and bbPress installed with defaults.

Anyone visits [site]/forums/users/[anything non-admin] gets a 404, which redirects to homepage.

Adding 404-to-301 exception for "/forums/users" stops the problem... which shouldn't happen in the first place, right?

**Comment by Joel-James** [comment]
Sorry for the late reply. Was busy with my job change. Can you check this with the current master branch from GitHub?

**Comment by i-make-robots** [comment]
my situation is a little odd right now.  can you push an update and I'll test that, please?

**Comment by i-make-robots** [comment]
seems ok with the current version.  maybe some other plugin is turned off?

**Comment by Joel-James** [comment]
Released new version
