### ISSUE TITLE
Warning: strpos(): Empty needle in ***/wp-content/plugins/404-to-301/public/class-404-to-301-public.php on line 347

### ISSUE THREAD

**Issue by wilsonf1** [Joel-James/404-to-301#38]
We are getting this error on our 404 page:

Warning: strpos(): Empty needle in ***/wp-content/plugins/404-to-301/public/class-404-to-301-public.php on line 347

Any ideas?

**Comment by Joel-James** [comment]
This is fixed in new version which is in master branch
